name: Bug Report
description: Create a report to help us improve
title: "[Bug]: "
labels: ["bug"]
assignees: []

body:
  - type: input
    id: bug-description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the issue...
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please provide details about your environment
      value: |
        **OS:** [e.g. Ubuntu 20.04, Windows 10, macOS Big Sur]
        **Version:** [e.g. 22.04]
        **Python Version:** [e.g. 3.9.7]
        **Framework:** [e.g. PyTorch 1.12.0, TensorFlow 2.8.0]
        **Hardware:** [e.g. GPU: RTX 3080, CPU: Intel i7-9700K]
      placeholder: Provide environment details...
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: What steps did you take?
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: What should happen...

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: A clear and concise description of what actually happened.
      placeholder: What happened instead...

  - type: textarea
    id: code-snippet
    attributes:
      label: Code Snippet
      description: Include relevant code that caused the bug
      placeholder: ```python
                  # Your code here
                  ```

  - type: textarea
    id: error-message
    attributes:
      label: Error Message
      description: Include the full error message if applicable
      placeholder: ```
                  Full error message here
                  ```

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
      placeholder: Any other relevant information...

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this issue?
      options:
        - "Low - Minor issue, doesn't affect core functionality"
        - "Medium - Issue affects some functionality but has workaround"
        - "High - Issue prevents core functionality from working"
        - "Critical - Issue breaks essential functionality"
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How urgent is this fix?
      options:
        - "Low - Can be addressed in future releases"
        - "Medium - Should be addressed in next minor version"
        - "High - Needs to be addressed urgently"
        - "Critical - Must be fixed immediately"

  - type: checkboxes
    id: attachments
    attributes:
      label: Attachments
      description: What have you attached to this issue?
      options:
        - label: Screenshots/GIFs showing the issue
        - label: Log files
        - label: Sample data that triggers the issue